#!/usr/bin/env python3

import glob
import argparse
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument("job_pathPattern", help="The directory pattern where your Sun pictures will be cropped and stacked from")
parser.add_argument("--crop_threshold", help="Threshold of min pixel value to consider as part of the solar disk", type=int, default=50)
parser.add_argument("--crop_margin", help="Margin around the Solar Limb", type=int, default=50)
parser.add_argument("--stack_percent", help="Stack percent", type=int, default=100)
parser.add_argument("--unsharp_radius", help="Unsharp radius", type=int, default=10)
parser.add_argument("--unsharp_sigma", help="Unsharp sigma", type=int, default=4)
parser.add_argument("--unsharp_amount", help="Unsharp amount", type=int, default=1)
parser.add_argument("--unsharp_threshold", help="Unsharp threshold", type=int, default=0)
args = parser.parse_args()

filenames_list = glob.glob(args.job_pathPattern)

if len(filenames_list) == 0:
    raise RuntimeError("Directory pattern '%s' doesn't return any files" %args.job_pathPattern)

print("Cropping Solar Limb...")
pargs = ["/opt/wolfdotsolar/crop_sun", args.job_pathPattern]
subprocess.call(pargs) 

print("Stacking Solar Limb...")
pargs = ["PlanetarySystemStacker", "/imgs/wolfdotsolar/", "--stack_percent=" + str(args.stack_percent)]
subprocess.call(pargs)

print("Unsharping Solar Limb...")
pargs = ["/opt/wolfdotsolar/unsharp", "/imgs/wolfdotsolar/_pss.png", "--amount=3", "--sigma=3", "--radius=100"]
subprocess.call(pargs)

print("Done.")